// SPDX-License-Identifier: Apache-2.0

export enum AssetType {
  EQUITY = "EQUITY",
  BOND_VARIABLE_RATE = "BOND_VARIABLE_RATE",
  BOND_FIXED_RATE = "BOND_FIXED_RATE",
  BOND_KPI_LINKED_RATE = "BOND_KPI_LINKED_RATE",
  BOND_SPT_RATE = "BOND_SPT_RATE",
}
