// SPDX-License-Identifier: Apache-2.0

export enum RouteName {
  Landing = "LANDING",
  Dashboard = "DASHBOARD",
  ExternalControlList = "EXTERNAL_CONTROL_LIST",
  ExternalControlDetails = "EXTERNAL_CONTROL_DETAILS",
  CreateExternalControl = "CREATE_EXTERNAL_CONTROL",
  AddExternalControl = "ADD_EXTERNAL_CONTROL",
  ExternalPauseList = "EXTERNAL_PAUSE_LIST",
  CreateExternalPause = "CREATE_EXTERNAL_PAUSE",
  AddExternalPause = "ADD_EXTERNAL_PAUSE",
  ExternalKYCList = "EXTERNAL_KYC_LIST",
  ExternalKYCDetails = "EXTERNAL_KYC_DETAILS",
  CreateExternalKYC = "CREATE_EXTERNAL_KYC",
  AddExternalKYC = "ADD_EXTERNAL_KYC",
  AddSecurity = "ADD_SECURITY",
  CreateSecurity = "CREATE_SECURITY",
  CreateEquity = "CREATE_EQUITY",
  CreateBond = "CREATE_BOND",
  DigitalSecurityDetails = "DIGITAL_SECURITY_DETAILS",
  DigitalSecuritiesList = "DIGITAL_SECURITIES_LIST",
  DigitalSecurityMint = "DIGITAL_SECURITY_MINT",
  DigitalSecurityFreeze = "DIGITAL_SECURITY_FREEZE",
  DigitalSecurityTransfer = "DIGITAL_SECURITY_TRANSFER",
  DigitalSecurityForceTransfer = "DIGITAL_SECURITY_FORCE_TRANSFER",
  DigitalSecurityRedeem = "DIGITAL_SECURITY_REDEEM",
  DigitalSecurityForceRedeem = "DIGITAL_SECURITY_FORCE_REDEEM",
  DigitalSecurityLock = "DIGITAL_SECURITY_LOCK",
}
